### ISSUE TITLE
VERY BIG ISSUE VERY BAD

### ISSUE THREAD

**Issue by KAUTARUMA** [oscie57/DSiTorch#2]
i opened the video game and my ds exploded and made me die and bleed please fix....

**Comment by oscie57** [comment]
oh no! sadly, warranty doesnt cover your life. suck it up and try again later ❤️  this has happened before to many of our clients, so we do hope you recover well, though youre dead, so, skill issue ig

**Comment by Minyatan** [comment]
Ok Thank You
